"""empty message

Revision ID: 06baaab181f8
Revises: 6ab8c670a5b8
Create Date: 2018-04-09 21:27:09.147218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06baaab181f8'
down_revision = '6ab8c670a5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('hours_a_day', sa.Time(), nullable=True))
    op.add_column('employee_time', sa.Column('hours_a_week', sa.Numeric(), nullable=True))
    op.drop_column('employee_time', 'hrs_a_week')
    op.drop_column('employee_time', 'hrs_a_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('hrs_a_day', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('employee_time', sa.Column('hrs_a_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('employee_time', 'hours_a_week')
    op.drop_column('employee_time', 'hours_a_day')
    # ### end Alembic commands ###
