"""empty message

Revision ID: 1abef350ab54
Revises: 76d08a9466b4
Create Date: 2018-04-24 02:17:50.422741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abef350ab54'
down_revision = '76d08a9466b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('flexi', sa.String(), nullable=True))
    op.drop_column('employee_time', 'flexit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('flexit', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('employee_time', 'flexi')
    # ### end Alembic commands ###
