"""empty message

Revision ID: 3c2ae4e835b2
Revises: 8ed58a38e3f3
Create Date: 2018-04-08 17:26:31.329036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2ae4e835b2'
down_revision = '8ed58a38e3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('flexi', sa.Time(), nullable=True))
    op.drop_column('employee_time', 'flexi_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('flexi_total', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('employee_time', 'flexi')
    # ### end Alembic commands ###
