"""empty message

Revision ID: 3c6288cd24af
Revises: 06baaab181f8
Create Date: 2018-04-11 22:45:13.121081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6288cd24af'
down_revision = '06baaab181f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_time', 'last_updated')
    # ### end Alembic commands ###
