"""empty message

Revision ID: 76d08a9466b4
Revises: 3c6288cd24af
Create Date: 2018-04-24 02:17:04.749088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76d08a9466b4'
down_revision = '3c6288cd24af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('flexit', sa.Numeric(), nullable=True))
    op.drop_column('employee_time', 'flexi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_time', sa.Column('flexi', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('employee_time', 'flexit')
    # ### end Alembic commands ###
