"""add admin check column

Revision ID: b8acd02a3da7
Revises: 91bf0beab4ad
Create Date: 2018-03-07 19:21:34.079891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8acd02a3da7'
down_revision = '91bf0beab4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'is_admin')
    # ### end Alembic commands ###
