"""empty message

Revision ID: cdedad9e57be
Revises: 1abef350ab54
Create Date: 2018-04-30 02:08:44.219184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdedad9e57be'
down_revision = '1abef350ab54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_record', sa.Column('sufficient', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_record', 'sufficient')
    # ### end Alembic commands ###
