"""empty message

Revision ID: d063acb2dbf7
Revises: cdedad9e57be
Create Date: 2018-05-12 21:15:38.674114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd063acb2dbf7'
down_revision = 'cdedad9e57be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_record', sa.Column('absent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_record', 'absent')
    # ### end Alembic commands ###
